### PR TITLE
Improved get_info()

### PR DESCRIPTION
**Pull request by TheFenrisLycaon**
Improved get_info() to give out the "Optional Dependencies" items as a nested dictionary instead of creating a new feature for every dependency. Check screenshots for better understanding of the problem.

problem
solution

### CODE REVIEW

**Comment by TheFenrisLycaon** [comment]
Tested on 917 packages. Works. [Example](https://paste.ee/p/dbjaC)

**Comment by tallero** [comment]
What do you think of using ipython-style docstrings?

**Comment by tallero** [comment]
I am using it [here](https://github.com/tallero/misc/blob/master/arch/which_package_depends_on).

I'm trying to make an encrypted rootfs live cd.

**Comment by peakwinter** [comment]
@TheFenrisLycaon Thanks for the contribution!

**Pull request merged**
